In [ ]:
# # Read Instructions carefully before attempting this assignment

# 1) don't rename any function name
# 2) don't rename any variable name
# 3) don't remove any #comment 
# 4) don't remove """ under triple quate values """
# 5) you have to write code where you found "write your code here"
# 6) after download rename this file with this format "PIAICCompletRollNumber_AssignmentNo.py"
#   Example piaic17896_Assignment1.py
# 7) After complete this assignment please push on your own GitHub repository.
# 8) you can submit this assignment through the google form
# 9) copy this file absolute URL then paste in the google form
#  The example above: https://github.com/EnggQasim/Batch04_to_35/blob/main/Sunday/1_30%20to%203_30/Assignments/assignment1.txt

# * Because all assignment we will be checked through software if you missed any above points 
# * then we can't assign your scores in our database.

In [ ]:
import numpy as np

# Task no 1
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    x =  np.arange(1,13).reshape((6,2)) 

    return x
    """
    expected output:
    [[ 1  2]
    [ 3  4]
    [ 5  6]
    [ 7  8]
    [ 9 10]
    [11 12]]
    """

In [ ]:
import numpy as np

In [ ]:
x=np.arange(1, 13).reshape((6, 2))

In [ ]:
x

In [ ]:
# Task2
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    x = np.arange(1,28,dtype=np.float64).reshape((3,3,3))     #wrtie your code here


    return x
    """
    Expected: out put
array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])    
    """

In [ ]:
x = np.arange(10, 37, dtype=np.float64).reshape((3, 3, 3))

In [ ]:
x

In [ ]:
#task3
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = a[] #wrtie your code here
    return x
    """
    Expected Output:
     [35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980] 
    """ 

In [ ]:
a = np.arange(1, 100 * 10 + 1).reshape((100, 10))

In [ ]:
x = a[(a%5==0) & (a%7==0)]

In [ ]:
x

In [ ]:
#task4
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
  
    return #wrtie your code here
    """
    Expected Output:
          array([[1, 0, 2],
                [4, 3, 5],
                [7, 6, 8]])
    """ 

In [ ]:
arr=np.arange(9).reshape(3, 3)

In [ ]:
arr[:,[0,1]]=arr[:,[1,0]]

In [ ]:
arr

In [ ]:
#task5
def function5():
    #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
   
    z = #wrtie your code here
  
    return z
    """
    Expected Output:
          array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]])
    """ 

In [ ]:
z = np.zeros(20) .reshape(4,5)

In [ ]:
z

In [ ]:
#task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
    arr =arr =np.zeros(20)
    #wrtie your code here
  
    return

In [ ]:
arr =arr =np.zeros(20)

In [ ]:
arr[4]=10


In [ ]:
arr[7]=20

In [ ]:
arr

In [ ]:
#task7
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
  
    return  #write your code here

    """
    Expected Output:
          array([0, 0, 0, 0], dtype=int64)
    """ 

In [ ]:
x = np.arange(4, dtype=np.int64)

In [ ]:
x[::]=0

In [ ]:
x

In [ ]:
#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x = #write your code here
  
    return x

     """
     Expected Output:
              array([[6, 6, 6, 6, 6],
                     [6, 6, 6, 6, 6]], dtype=uint32)
     """ 

In [ ]:
x = np.arange(10, dtype=np.int64) .reshape(2,5)

In [ ]:
x[::]=6

In [ ]:
x

In [ ]:
#task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a = # write your code here
  
    return a

     """
     Expected Output:
              array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
                    28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
                    54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
                    80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])
     """ 

In [ ]:
a = np.arange(2,102,2)

In [ ]:
a

In [ ]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = # write your code here 
  
    return subt

     """
     Expected Output:
               array([[2 2 2]
                      [2 2 2]
                      [2 2 2]])
     """ 

In [ ]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
arr

In [ ]:
brr = np.array([1,2,3])

In [ ]:
subt = arr-brr[:,None]

In [ ]:
subt

In [ ]:
#task11
def function11():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = #write your code here 
  
    return ans

     """
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
     """ 

In [ ]:
arr = np.array([1,2,3])

In [ ]:
ans = np.r_[np.repeat(arr,3), np.tile(arr,3)]

In [ ]:
ans

In [ ]:
#task12
def function12():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans = #write your code here 
  
    return ans

     """
     Expected Output:
              array([6, 9])
     """

In [ ]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])

In [ ]:
ans =arr[(arr>5) & (arr<10)]

In [ ]:
ans

In [ ]:
#task13
def function13():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
    arr = numpy.arange(10, 34, 1) #write reshape code
    ans = #write your code here 
  
    return ans

     """
     Expected Output:
       [array([[10, 11, 12],[13, 14, 15]]), 
        array([[16, 17, 18],[19, 20, 21]]), 
        array([[22, 23, 24],[25, 26, 27]]), 
        array([[28, 29, 30],[31, 32, 33]])]
     """ 

In [ ]:
arr = np.arange(10, 34, 1) .reshape(8,3)


In [ ]:
ans = np.split(arr,4)

In [ ]:
ans

In [ ]:
#task14
def function14():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    ans = #write your code here 
  
    return ans

     """
     Expected Output:
                [[[1 2]]

                 [[2 3]]

                 [[3 4]]]
     """

In [ ]:
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])

In [ ]:
ans = np.dstack((x,y))

In [ ]:
ans

In [ ]:
#Task15
def function15():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    return           # Write Your Code HERE

#Excpected Out
"""
array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')
"""

In [ ]:
arr = np.arange(1,10*10+1).reshape((10,10))


In [ ]:
ans= np.where((arr % 3==0) & (arr % 5==0), "YES", "NO" )

In [ ]:
ans

In [ ]:
#Task16
def fucntion16():
    #apply fuction "abc" on each value of Array "X"
    x = np.arange(1,11)
    def xyz(x):
        return x*2+3-2

    return #Write your Code here
#Expected Output: array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [ ]:
x = np.arange(1, 11)

In [ ]:
def abc(x):
        return x*2+3-2

In [ ]:
abc(x)